Metrics/BlockLength:
  Exclude:
    - 'spec/*'
Layout/LineLength:
  Exclude:
    - 'spec/*'
AllCops:
  NewCops: enable
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/FrozenStringLiteralComment:
  EnforcedStyle: never